<a href="https://colab.research.google.com/github/bargida/AI_codes/blob/main/Workshop_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# --------------------------------------- Training -------------------------------------

* You can check the comments to see what each cell does. First, read the comments, and then run the cells to see the outputs.


* There are a few exercises in the notebook. The solution of some of them is given. But please first try to complete the exercise yourself and then look at the solution.


* After running all cells and completing all exercises, complete the tasks at the end of the notebook.

## Importing necessary Libraries

In [16]:
import pandas as pd
import numpy as np
from google.colab import files
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

## Importing a dataset for this workshop

## Importing the dataset directly from the source

In [17]:
# Installing a package which is needed to download the dataset from its online source. This package is recommended by the online source at the following
# URL : https://archive.ics.uci.edu/dataset/2/adult. You need to reinstall the kernel after the package has been installed
!pip3 install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [18]:
# Downloading the dataset from the online source. The first two lines are given by the online source mentioned above
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
_orig_create_default_context = ssl.create_default_context
def unverified_context(*args, **kwargs):
    return ssl._create_unverified_context()
ssl.create_default_context = unverified_context

from ucimlrepo import fetch_ucirepo
# fetch dataset
adult = fetch_ucirepo(id=2)

# Putting data in a pandas dataframe
X = adult.data.features
y = adult.data.targets
data=pd.concat([X,y],axis=1)
# Save the data locally to adult.csv so that Cell 10 (pd.read_csv('adult.csv')) runs successfully
data.to_csv('adult.csv', index=False)

In [20]:
#printing data
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

## Importing the dataset from a folder on your local disk

In [21]:
#importing the dataset as a Pandas DataFrame into Python if the dataset is stored on your local hard disk
# You can download the dataset from the following URL: https://archive.ics.uci.edu/dataset/2/adult
data = pd.read_csv('adult.csv') # Replace the current data path with the data path on your local disk

## Exploring the dataset

In [22]:
# Showing the first 5 rows of the dataset
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [23]:
# Finding the shape of the data
print(data.shape)

(48842, 15)

In [24]:
# Generate a dataset by randomly extracting 30000 rows (samples)
data_new = data.sample(n=30000, random_state = 48)

In [25]:
# Printing the new dataset
data_new

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
8029,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
45203,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K.
27498,25,?,100903,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,25,United-States,<=50K
48416,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K.
43230,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37544,20,Private,166371,HS-grad,9,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K.
20482,80,Private,202483,HS-grad,9,Married-spouse-absent,Adm-clerical,Not-in-family,White,Female,0,0,16,United-States,<=50K
39667,20,Private,175808,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
40001,25,State-gov,31350,Some-college,10,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
48523,19,Private,239057,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.

In [26]:
# The indices of different rows in the dataset are currently messy. This happens in many data science projects. Always reindex
# the dataset if you are unsure the indices are correct.
data_new.reset_index(drop=True, inplace=True)

In [27]:
# Checking if the indices are correct
data_new

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
1,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K.
2,25,?,100903,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,25,United-States,<=50K
3,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K.
4,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,20,Private,166371,HS-grad,9,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K.
29996,80,Private,202483,HS-grad,9,Married-spouse-absent,Adm-clerical,Not-in-family,White,Female,0,0,16,United-States,<=50K
29997,20,Private,175808,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
29998,25,State-gov,31350,Some-college,10,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
29999,19,Private,239057,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.

In [28]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [29]:
# Getting statistical information of the dataset for different columns (features)
data.describe(include="all")

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,48842.000000,47879,4.884200e+04,48842,48842.000000,48842,47876,48842,48842,48842,48842.000000,48842.000000,48842.000000,48568,48842
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,4
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,33906,NaN,15784,NaN,22379,6172,19716,41762,32650,NaN,NaN,NaN,43832,24720
mean,38.643585,NaN,1.896641e+05,NaN,10.078089,NaN,NaN,NaN,NaN,NaN,1079.067626,87.502314,40.422382,NaN,NaN
std,13.710510,NaN,1.056040e+05,NaN,2.570973,NaN,NaN,NaN,NaN,NaN,7452.019058,403.004552,12.391444,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.175505e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.781445e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.376420e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.490400e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [30]:
# Showing the dataset information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48568 non-null  object
 14  income          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [31]:
# Getting the count of different values in the column "education-num"
data['education-num'].value_counts()

education-num
9     15784
10    10878
13     8025
14     2657
11     2061
7      1812
12     1601
6      1389
4       955
15      834
5       756
8       657
16      594
3       509
2       247
1        83
Name: count, dtype: int64

In [32]:
# Getting the count of different values in the column "education"
data['education'].value_counts()

education
HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: count, dtype: int64

In [39]:
# Dropping a column
data = data.drop(['fnlwgt'], axis=1, errors='ignore')

In [40]:
data.shape

(48842, 14)

In [41]:
# Getting the number of unique values of a column
data['education'].nunique()

16

In [36]:
# Finding how many rows are related to either gender
data['sex'].value_counts()

sex
Male      32650
Female    16192
Name: count, dtype: int64

In [42]:
# Calculating the average age of different genders in the dataset
data['age'].groupby([data['sex']]).mean()

sex
Female    36.927989
Male      39.494395
Name: age, dtype: float64

In [43]:
# Getting the average age of different genders in the dataset broken down based on their education
data['age'].groupby([data['sex'],data['education']]).mean()

sex     education
Female  10th            36.474836
        11th            29.963077
        12th            29.469194
        1st-4th         47.098361
        5th-6th         45.362205
        7th-8th         50.577406
        9th             41.272727
        Assoc-acdm      36.508772
        Assoc-voc       38.111717
        Bachelors       35.880904
        Doctorate       45.557522
        HS-grad         38.910339
        Masters         42.665089
        Preschool       44.083333
        Prof-school     39.878788
        Some-college    33.552657
Male    10th            38.603004
        11th            33.360585
        12th            33.544843
        1st-4th         46.489247
        5th-6th         42.994764
        7th-8th         49.174581
        9th             40.750000
        Assoc-acdm      38.593429
        Assoc-voc       38.949510
        Bachelors       40.242610
        Doctorate       47.993763
        HS-grad         39.151773
        Masters         44.632450
        Preschool       41.440678
        Prof-school     46.143875
        Some-college    37.001791
Name: age, dtype: float64

In [44]:
# Getting the maximum age of different races in the dataset
data['age'].groupby([data['race']]).max()

race
Amer-Indian-Eskimo    82
Asian-Pac-Islander    90
Black                 90
Other                 77
White                 90
Name: age, dtype: int64

* Exercise 1: Write a code to find how much contribution each sex and occupation category made to the capital-gain on average. Apply the code to the dataset and print the result

In [48]:
# Extracting the age and education columns and creating a new DataFrame using these columns
a=data['age']
b=data['education']
new_data=pd.concat([a,b],axis=1)

In [46]:
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [52]:
data['capital-gain'].groupby([data['sex'], data['occupation']]).mean()

sex     occupation
Female  ?                     337.712247
        Adm-clerical          465.291059
        Craft-repair          728.386997
        Exec-managerial      1204.303204
        Farming-fishing       707.757895
        Handlers-cleaners     503.771654
        Machine-op-inspct     140.941542
        Other-service         204.280578
        Priv-house-serv       193.929825
        Prof-specialty       1255.421499
        Protective-serv      1987.491803
        Sales                 268.101181
        Tech-support          525.453737
        Transport-moving      481.118110
Male    ?                     828.404192
        Adm-clerical          501.070575
        Armed-Forces          486.533333
        Craft-repair          718.425635
        Exec-managerial      2710.303827
        Farming-fishing       716.494624
        Handlers-cleaners     252.625413
        Machine-op-inspct     378.404418
        Other-service         232.705618
        Priv-house-serv        42.428571
        Prof-specialty       3596.221628
        Protective-serv       537.052265
        Sales                1813.611189
        Tech-support          762.796380
        Transport-moving      439.288151
Name: capital-gain, dtype: float64

* Exercise 2: Write a function that receives the dataset and replace Famle with F and Male with M (please try to write it yourself before checking the answer in the next cell)

In [49]:
# exercise 2 solution
def encode_sex(data):
    data.reset_index(drop=True, inplace=True) # reindexing the dataset in case the dataset index is corrupted
    rows=data.shape[0]
    a=data.loc[:,'sex']
    for i in range(rows):
        if a[i]=="Male":
            data.loc[i,"sex"]="M"
        elif a[i]=="Female":
            data.loc[i,"sex"]="F"
    return data

In [50]:
# Copying the data
data_copy=data.copy()

In [51]:
# Applying the encode_sex function to the copied data
data_encoded=encode_sex(data_copy)
data_encoded.head()

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,M,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,M,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,M,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,M,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,F,0,0,40,Cuba,<=50K

In [53]:
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

# Tasks

## P 2.1: Complete the following steps (4%):
## 1- Import the dataset from the URL we used in this workshop.
## 2- Generate a new dataset by randomly extracting 10000 samples.
## 3- Drop the 'income' column, reindex the new dataset and then clean it.
## 4- Print the new dataset and use it for the rest of the tasks

In [55]:
############# WRITE YOUR CODE IN THIS CELL (IF APPLICABLE)  ####################
import pandas as pd
data = pd.read_csv('adult.csv')
str_cols = data.select_dtypes(include='object').columns
data[str_cols] = data[str_cols].apply(lambda c: c.str.strip())

# randomly 10000 samples
data_new = data.sample(n=10000, random_state=48)

# drop 'income', clean
data_new = data_new.drop(['income'], axis=1)
data_new.reset_index(drop=True, inplace=True)
data_new = data_new.replace('?', pd.NA).dropna()
data_new.reset_index(drop=True, inplace=True)

# print data
print(data_new.shape)
data_new

(9226, 14)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States
1,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States
2,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States
3,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States
4,37,Private,186808,HS-grad,9,Never-married,Sales,Unmarried,White,Male,0,0,40,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9221,19,Private,63363,Some-college,10,Never-married,Sales,Own-child,White,Female,0,0,30,United-States
9222,53,Private,58535,HS-grad,9,Divorced,Sales,Not-in-family,White,Female,0,0,40,United-States
9223,30,Private,342709,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,United-States
9224,41,Self-emp-not-inc,134724,Assoc-voc,11,Married-civ-spouse,Other-service,Wife,White,Female,3103,0,40,United-States
9225,21,Private,252253,Some-college,10,Never-married,Adm-clerical,Unmarried,Black,Female,0,0,40,United-States

############ WRITE YOUR REPORT IN THIS CELL (IF APPLICABLE) #############

## P 2.2: Complete the following steps (4%):
## 1- Determine which columns are categorical and which columns are numerical.
## 2- Encode the categorical columns using the correct method.
## 3- Normalise the numerical columns.
## 4- Print the dataset

In [59]:
############# WRITE YOUR CODE IN THIS CELL (IF APPLICABLE)  ####################
# from sklearn.preprocessing import LabelEncoder, MinMaxScaler

data_f = data_new.copy()

# identify categorical and numerical columns
categorical_cols = data_f.select_dtypes(include='object').columns.tolist()
numerical_cols   = data_f.select_dtypes(include='number').columns.tolist()

print("Categorical columns:", categorical_cols)
print("Numerical columns:  ", numerical_cols)

# encode categorical columns using Label Encoding
le = LabelEncoder()
for col in categorical_cols:
    data_f[col] = le.fit_transform(data_f[col])

# normalise numerical columns using Min-Max scaling (0 to 1)
scaler = MinMaxScaler()
data_f[numerical_cols] = scaler.fit_transform(data_f[numerical_cols])

# print
print(data_f)

Categorical columns: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
Numerical columns:   ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
           age  workclass    fnlwgt  education  education-num  marital-status  \
0     0.164384          2  0.146459         12       0.866667               2
1     0.260274          2  0.194042         15       0.600000               2
2     0.410959          2  0.093861          8       0.666667               2
3     0.219178          2  0.074399         11       0.533333               2
4     0.273973          2  0.124429         11       0.533333               4
...        ...        ...       ...        ...            ...             ...
9221  0.027397          2  0.032778         15       0.600000               4
9222  0.493151          2  0.029194         11       0.533333               0
9223  0.178082          2  0.240176         11       0.533333               2
9224  0.328767          4  0.085760          8       0.666667               2
9225  0.054795          2  0.173018         15       0.600000               4

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0              3             5     4    0       0.00000           0.0
1              2             0     4    1       0.00000           0.0
2              5             0     4    1       0.00000           0.0
3              3             0     4    1       0.00000           0.0
4             11             4     4    1       0.00000           0.0
...          ...           ...   ...  ...           ...           ...
9221          11             3     4    0       0.00000           0.0
9222          11             1     4    0       0.00000           0.0
9223           5             0     4    1       0.00000           0.0
9224           7             5     4    0       0.03103           0.0
9225           0             4     2    0       0.00000           0.0

      hours-per-week  native-country
0           0.391753              37
1           0.443299              37
2           0.474227              37
3           0.391753              37
4           0.391753              37
...              ...             ...
9221        0.288660              37
9222        0.391753              37
9223        0.391753              37
9224        0.391753              37
9225        0.391753              37

[9226 rows x 14 columns]

############ WRITE YOUR REPORT IN THIS CELL (IF APPLICABLE) #############

## P 2.3: Write a function to split the dataset in half column-wise and swap the first half and the second half. Apply the funtion to the dataset and print the result (3%)

In [60]:
############# WRITE YOUR CODE IN THIS CELL (IF APPLICABLE)  ####################
def swap_column_halves(df):
    cols = df.columns.tolist()
    mid = len(cols) // 2
    first_half = cols[:mid]
    second_half = cols[mid:]
    return df[second_half + first_half]

data_ = swap_column_halves(data_f.copy())
print(data_)

      relationship  race  sex  capital-gain  capital-loss  hours-per-week  \
0                5     4    0       0.00000           0.0        0.391753
1                0     4    1       0.00000           0.0        0.443299
2                0     4    1       0.00000           0.0        0.474227
3                0     4    1       0.00000           0.0        0.391753
4                4     4    1       0.00000           0.0        0.391753
...            ...   ...  ...           ...           ...             ...
9221             3     4    0       0.00000           0.0        0.288660
9222             1     4    0       0.00000           0.0        0.391753
9223             0     4    1       0.00000           0.0        0.391753
9224             5     4    0       0.03103           0.0        0.391753
9225             4     2    0       0.00000           0.0        0.391753

      native-country       age  workclass    fnlwgt  education  education-num  \
0                 37  0.164384          2  0.146459         12       0.866667
1                 37  0.260274          2  0.194042         15       0.600000
2                 37  0.410959          2  0.093861          8       0.666667
3                 37  0.219178          2  0.074399         11       0.533333
4                 37  0.273973          2  0.124429         11       0.533333
...              ...       ...        ...       ...        ...            ...
9221              37  0.027397          2  0.032778         15       0.600000
9222              37  0.493151          2  0.029194         11       0.533333
9223              37  0.178082          2  0.240176         11       0.533333
9224              37  0.328767          4  0.085760          8       0.666667
9225              37  0.054795          2  0.173018         15       0.600000

      marital-status  occupation
0                  2           3
1                  2           2
2                  2           5
3                  2           3
4                  4          11
...              ...         ...
9221               4          11
9222               0          11
9223               2           5
9224               2           7
9225               4           0

[9226 rows x 14 columns]

############ WRITE YOUR REPORT IN THIS CELL (IF APPLICABLE) #############

## P 2.4: Write a function that receives two numerical columns' names and compare their values for all rows. If the value of the first column is greater than the second column, the function should produce True, otherwise, it should produce False. The function should append an additional column to the dataset to store the results of the comparison for all rows. Apply the function to the "age" and "hours-per-week" columns in the dataset and print the result (4%).

In [61]:
############# WRITE YOUR CODE IN THIS CELL (IF APPLICABLE)  ####################
def compare_columns(df, col1, col2):
    result_col = f'{col1}_greater_than_{col2}'
    df[result_col] = df[col1] > df[col2]
    return df

data_2 = compare_columns(data_f.copy(), 'age', 'hours-per-week')
print(data_2)

           age  workclass    fnlwgt  education  education-num  marital-status  \
0     0.164384          2  0.146459         12       0.866667               2
1     0.260274          2  0.194042         15       0.600000               2
2     0.410959          2  0.093861          8       0.666667               2
3     0.219178          2  0.074399         11       0.533333               2
4     0.273973          2  0.124429         11       0.533333               4
...        ...        ...       ...        ...            ...             ...
9221  0.027397          2  0.032778         15       0.600000               4
9222  0.493151          2  0.029194         11       0.533333               0
9223  0.178082          2  0.240176         11       0.533333               2
9224  0.328767          4  0.085760          8       0.666667               2
9225  0.054795          2  0.173018         15       0.600000               4

      occupation  relationship  race  sex  capital-gain  capital-loss  \
0              3             5     4    0       0.00000           0.0
1              2             0     4    1       0.00000           0.0
2              5             0     4    1       0.00000           0.0
3              3             0     4    1       0.00000           0.0
4             11             4     4    1       0.00000           0.0
...          ...           ...   ...  ...           ...           ...
9221          11             3     4    0       0.00000           0.0
9222          11             1     4    0       0.00000           0.0
9223           5             0     4    1       0.00000           0.0
9224           7             5     4    0       0.03103           0.0
9225           0             4     2    0       0.00000           0.0

      hours-per-week  native-country  age_greater_than_hours-per-week
0           0.391753              37                            False
1           0.443299              37                            False
2           0.474227              37                            False
3           0.391753              37                            False
4           0.391753              37                            False
...              ...             ...                              ...
9221        0.288660              37                            False
9222        0.391753              37                             True
9223        0.391753              37                            False
9224        0.391753              37                            False
9225        0.391753              37                            False

[9226 rows x 15 columns]

############ WRITE YOUR REPORT IN THIS CELL (IF APPLICABLE) #############